# Generated by Django 4.2.2 on 2023-06-30 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/test_image.jpg', null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='PredictedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_days', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1)),
                ('big_cities', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('P2', models.FloatField()),
                ('P8', models.IntegerField()),
                ('P22', models.IntegerField()),
                ('P24', models.IntegerField()),
                ('P28', models.FloatField()),
                ('P26', models.FloatField()),
                ('results', models.TextField(default=None, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile')),
            ],
        ),
    ]
