# Generated by Django 4.2.2 on 2023-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_alter_profile_profile_img_predictedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmodel',
            name='P2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P22',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P24',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P26',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P28',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P8',
            field=models.TextField(),
        ),
    ]
