# Generated by Django 4.2.2 on 2023-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_predictedmodel_p2_alter_predictedmodel_p22_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmodel',
            name='P2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P22',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P24',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P26',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P28',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='P8',
            field=models.IntegerField(),
        ),
    ]
