# Generated by Django 4.2.2 on 2023-07-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_alter_predictedmodel_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='predictedmodel',
            name='name',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictedmodel',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile'),
        ),
    ]
