# Generated by Django 4.2.2 on 2023-07-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_remove_predictedmodel_user_predictedmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedmodel',
            name='name',
        ),
    ]
