# Generated by Django 4.2.2 on 2023-07-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_remove_predictedmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmodel',
            name='open_days',
            field=models.IntegerField(default=1),
        ),
    ]
