# Generated by Django 4.2.2 on 2023-07-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0011_remove_predictedmodel_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmodel',
            name='big_cities',
            field=models.BooleanField(default=True),
        ),
    ]
