# Generated by Django 4.2.2 on 2023-07-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0014_predictedmodel_p1_predictedmodel_p10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
