# Generated by Django 4.2.2 on 2023-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0015_remove_profile_desc_remove_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedmodel',
            name='city_name',
            field=models.TextField(default='Minsk', max_length=200),
        ),
    ]
