# Generated by Django 4.2.2 on 2023-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0016_predictedmodel_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedmodel',
            name='type',
            field=models.TextField(choices=[('IL', 'IL'), ('FC', 'FC')], default='IL'),
        ),
    ]
