# Generated by Django 4.2.2 on 2023-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0017_predictedmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmodel',
            name='big_cities',
            field=models.IntegerField(choices=[('True', 1), ('False', 2)]),
        ),
    ]
