# Generated by Django 4.2.2 on 2023-07-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0022_alter_predictedmodel_p1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictedmodel',
            old_name='P1',
            new_name='p1',
        ),
    ]
